### ISSUE TITLE
No documentation on Namespaces

### ISSUE THREAD

**Issue by ghost** [mikeroyal/PipeWire-Guide#21]
I recently gave Pipewire another chance and so far it seems OK. However I noticed many of my games that are jailed in NameSpaces no longer have audio. The old exporting PULSE_SERVER PULSE_COOKIE bit in the NameSpace no longer works so how do you grant the NameSpace access to PipeWire?

**Comment by nPHYN1T3** [comment]
I got desperate and tried a "different" [read: evil] search engine and finally found a match that was relevant. However it should have a section here given this is a guide that pipewire-0 will replace /pulse/native

so
export PULSE_SERVER=/run/user/$(id -u shed)/pulse/native
becomes
export PULSE_SERVER=$XDG_RUNTIME_DIR/pipewire-0

**Comment by ghost** [comment]
I got desperate and tried a "different" [read: evil] search engine and finally found a match that was relevant. However it should have a section here given this is a guide that pipewire-0 will replace /pulse/native

so
export PULSE_SERVER=$XDG_RUNTIME_DIR/pulse/native
becomes
export PULSE_SERVER=$XDG_RUNTIME_DIR/pipewire-0
