### ISSUE TITLE
Add the Ray Session session manager

### ISSUE THREAD

**Issue by ycollet** [mikeroyal/PipeWire-Guide#28]
Ray Session is a really nice session manager (like qpwgraph):
https://github.com/Houston4444/RaySession

**Comment by mikeroyal** [comment]
Okay, I'll take a look at it and possibly add it.

**Comment by mikeroyal** [comment]
Okay, I made a PR to add RaySession. Thank you for the reccomendation.

**Comment by ycollet** [comment]
Thanks a lot for you work !
