### ISSUE TITLE
Outdated instructions for Debian

### ISSUE THREAD

**Issue by tarikgraba** [mikeroyal/PipeWire-Guide#34]
The presented instructions were relevant for the old stable (Debian 11) version.
Since Debian 12, pipewire is more mature and easy to install with the pipewire-audio meta package.

You should remove the instructions and just keep the link ti Debain's wiki.
Eventually adding a note about the fact that newer versions are available in the backports repo.

Thanks for keeping this valuable resource online.

**Comment by mikeroyal** [comment]
I'll keep the instructions for those still using [Debian 10 and 11](https://wiki.debian.org/LTS). I will just add a note at the top saying Debian 12 comes with PipeWire already installed and setup.

**Comment by tarikgraba** [comment]
Thanks!
